# Generated by Django 5.2.8 on 2025-11-24 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('idEmpleado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('departamento', models.CharField(max_length=100)),
                ('sueldo', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
